---
version: '2.1'

# See: https://github.com/almenscorner/IntuneCD

services:
  intunecd:
    #image: 
    build: .
    container_name: intunecd
    hostname: intunecd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp:/tmp:rw
      #- /home/intunecd/config/:/config:ro
      #- /home/intunecd/output/:/output:rw
    command: "-o yaml -p /output -a /config/auth_DEV.json"
